### ISSUE TITLE
Pinch zoom not working on mobile

### ISSUE THREAD

**Issue by jhappone** [googlemaps/js-markerclustererplus#75]
Hi!

I'm having a problem with pinch-zooming on mobile browsers. In the mobile, if you pinch zoom by **not** touching the cluster-icons, it works, but if you pinch zoom over marker icon, depending on the meta viewport settings, it either zooms the whole viewport or does not zoom at all.

I tried @alexmccabe version (https://gist.github.com/alexmccabe/510dc73e27c7c04be669dff96f0acbd9) where pinch zooming works. But I have some code which hides/shows markers inside the cluster and that only works with the latest release.

I'm kinda stuck now between these two versions. I need to either try to get "old" version working with my marker hiding/showing code, or hopefully get the latest version working with pinch zoom.

I'm happy to help if needed.

Br,
Jukka

**Comment by thexs-dev** [comment]
I managed to reproduce this issue in mobile phones, both Android and iPhone, using @googlemaps/markerclustererplus version 1.0.3
- I had to carefully put two fingers at the same time within the 101-cluster (image 1)
- then zoom, to actually zoom the cluster image instead of the map (image 2)

Screenshots below

Image 1
![image](https://user-images.githubusercontent.com/11319351/102564458-7c0fe800-40a9-11eb-9ff8-691ff3a9206d.png)

Image 2
![image](https://user-images.githubusercontent.com/11319351/102564503-9649c600-40a9-11eb-9150-0c519ea45655.png)

**Comment by jpoehnelt** [comment]
It might be worth considering the recently refactored version of this library now found at https://github.com/googlemaps/js-markerclusterer.

**Comment by alexmccabe** [comment]
It's cool that there is a completely refactored version now. I'm loooong out of the codebase where I had to do the original changes, but hopefully this new version resolves many of the issues that people are having.

**Comment by jpoehnelt** [comment]
See #300.
